<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.microintegrator.projects</groupId>
    <artifactId>test-consolidated-devant</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>
    <name>test-consolidated-devant</name>
    <modules>
        <module>module-01</module>
        <module>module-02</module>
        <module>module-03</module>
    </modules>
    <properties>
        <project.runtime.version>4.6.0</project.runtime.version>
        <projectType>integration-project</projectType>     
        <car.plugin.version>5.4.16</car.plugin.version>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <is.consolidated.project>true</is.consolidated.project>
        <dockerfile.base.image>wso2/wso2mi:${project.runtime.version}</dockerfile.base.image>
    </properties>
</project>
